### ISSUE TITLE
Cannot seem to nail down dependencies

### ISSUE THREAD

**Issue by snhirsch** [feklee/vncdesk#13]
Running on Centos 7.3 (company standard) and have it to this point:

`vncdesk 2 xfig
Traceback (most recent call last):
  File "/usr/bin/vncdesk", line 3, in <module>
    import vncdesk
  File "/usr/lib/python3.4/site-packages/vncdesk/__init__.py", line 1, in <module>
    from .main import main
  File "/usr/lib/python3.4/site-packages/vncdesk/main.py", line 5, in <module>
    gi.require_version('GtkVnc', '2.0')
  File "/usr/lib64/python3.4/site-packages/gi/__init__.py", line 103, in require_version
    (namespace, version))
ValueError: Namespace GtkVnc not available for version 2.0
'
Obviously still missing something, but what?

**Comment by feklee** [comment]
Does the issue persist?

Sorry for not replying earlier!

**Comment by ghost** [comment]
This problem occurs in Mint 18.3 also.
Using `sudo -H pip3 install ` to install results in this error when vncdesk is run
```
Traceback (most recent call last):
  File "/usr/local/bin/vncdesk", line 3, in <module>
    import vncdesk
  File "/usr/local/lib/python3.5/dist-packages/vncdesk/__init__.py", line 1, in <module>
    from .main import main
  File "/usr/local/lib/python3.5/dist-packages/vncdesk/main.py", line 5, in <module>
    gi.require_version('GtkVnc', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkVnc not available
```
but using `sudo python3 setup.py install` gives
```
Traceback (most recent call last):
  File "/usr/local/bin/vncdesk", line 4, in <module>
    __import__('pkg_resources').run_script('vncdesk==1.7.0', 'vncdesk')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1518, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/vncdesk' not found in metadata at '/usr/local/lib/python3.5/dist-packages/vncdesk-1.7.0-py3.5.egg-info'
```

**Comment by feklee** [comment]
Thanks for the report!

*Can you please describe step by step how you installed Vncdesk? (incl. gtk-vnc 0.5 or compatible with Python GTK+ 3 bindings)*

Then I can try reproducing the issue in a virtual machine with Mint (first need to set that up).

**Comment by ghost** [comment]
Hi Felix, 

I already have python 2.7 and 3.5 installed.
I installed tigervnc 1.8.0-1ubuntu1_amd64, libgtk-vnc-2.0-0 0.5.3-1.3ubuntu2.1
and python-gtk-vnc 0.5.3-1.3ubuntu2.1

After downloading vncdesk I ran `sudo python3 setup.py install`
```
running install
running bdist_egg
running egg_info
writing dependency_links to vncdesk.egg-info/dependency_links.txt
writing vncdesk.egg-info/PKG-INFO
writing top-level names to vncdesk.egg-info/top_level.txt
reading manifest file 'vncdesk.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'vncdesk.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/vncdesk
copying build/lib/vncdesk/__init__.py -> build/bdist.linux-x86_64/egg/vncdesk
copying build/lib/vncdesk/d3des.py -> build/bdist.linux-x86_64/egg/vncdesk
copying build/lib/vncdesk/main.py -> build/bdist.linux-x86_64/egg/vncdesk
copying build/lib/vncdesk/util.py -> build/bdist.linux-x86_64/egg/vncdesk
copying build/lib/vncdesk/version.py -> build/bdist.linux-x86_64/egg/vncdesk
copying build/lib/vncdesk/vnc_server.py -> build/bdist.linux-x86_64/egg/vncdesk
byte-compiling build/bdist.linux-x86_64/egg/vncdesk/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/vncdesk/d3des.py to d3des.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/vncdesk/main.py to main.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/vncdesk/util.py to util.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/vncdesk/version.py to version.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/vncdesk/vnc_server.py to vnc_server.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.5/vncdesk -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/vncdesk to 755
copying vncdesk.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vncdesk.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vncdesk.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vncdesk.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vncdesk.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/vncdesk-1.7.0-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing vncdesk-1.7.0-py3.5.egg
Removing /usr/local/lib/python3.5/dist-packages/vncdesk-1.7.0-py3.5.egg
Copying vncdesk-1.7.0-py3.5.egg to /usr/local/lib/python3.5/dist-packages
vncdesk 1.7.0 is already the active version in easy-install.pth
Installing vncdesk script to /usr/local/bin

Installed /usr/local/lib/python3.5/dist-packages/vncdesk-1.7.0-py3.5.egg
Processing dependencies for vncdesk==1.7.0
Finished processing dependencies for vncdesk==1.7.0
```
Running vncdesk gives
```
Traceback (most recent call last):
  File "/usr/local/bin/vncdesk", line 4, in <module>
    __import__('pkg_resources').run_script('vncdesk==1.7.0', 'vncdesk')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1518, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/vncdesk' not found in metadata at '/usr/local/lib/python3.5/dist-packages/vncdesk-1.7.0-py3.5.egg-info'
```
I then tried reinstalling using pip3 `sudo -H pip3 install .`
```
Processing /home/adjco/Downloads/Software/vncdesk
Installing collected packages: vncdesk
  Found existing installation: vncdesk 1.7.0
    Uninstalling vncdesk-1.7.0:
      Successfully uninstalled vncdesk-1.7.0
  Running setup.py install for vncdesk ... done
Successfully installed vncdesk-1.7.0
```
Now running vncdesk gives
```
Traceback (most recent call last):
  File "/usr/local/bin/vncdesk", line 3, in <module>
    import vncdesk
  File "/usr/local/lib/python3.5/dist-packages/vncdesk/__init__.py", line 1, in <module>
    from .main import main
  File "/usr/local/lib/python3.5/dist-packages/vncdesk/main.py", line 5, in <module>
    gi.require_version('GtkVnc', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkVnc not available
```
So the installation does not show any errors, but vncdesk does not run. I just
have your xfig example in ~/.vncdesk/1/

Alan

**Comment by feklee** [comment]
Thanks, Alan!

In the description of [python-gtk-vnc 0.5.3-1.3ubuntu2.1](https://packages.ubuntu.com/xenial/python/python-gtk-vnc) it says: *VNC viewer widget for GTK+2 (Python binding)*

However, in the requirements of Vncdesk, it says: *gtk-vnc 0.5 or compatible, with Python GTK+ 3 bindings*.

[vncdesk-git](https://aur.archlinux.org/packages/vncdesk-git/), the package for Arch Linux depends on Arch's package [gtk-vnc](https://www.archlinux.org/packages/extra/x86_64/gtk-vnc/). Build instructions can be found in [PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gtk-vnc).

*Does that help?*

**Comment by ghost** [comment]
Hi Felix
I downloaded the gtk-vnc 0.7.2, built as per instructions in PKGBUILD and the result was the same as before. gtk-vnc depends on GTK+ 3, but if one builds it for GTK+ 3 it does not create the python bindings.
Configure summary:
```
        Compiler ...................:  gcc
        Compiler Flags .............:  -g -O2
        Extra Link Flags ...........:  -Wl,--version-script= -Wl,--no-undefined
        Prefix......................:  /usr

        Python binding .............:  no
        Install example programs ...:  yes
        SASL support................:  yes
        PulseAudio support..........:  yes
        GTK+ version................:  3.0
        TLS priority................:  NORMAL
```
 The configure script contains:
```
PYTHON_REQUIRED=2.4
-snip-
if test "$with_gtk" = "3.0"
then
  WITH_PYTHON=no
else
  WITH_PYTHON=$withval
fi
```
It looks like vncdesk has a dependency that is impossible to satisfy.

Alan

**Comment by feklee** [comment]
On my Arch system, I now also built the `gtc-vnc` package manually, according to `PKGBUILD`:

    $ git clone https://git.gnome.org/browse/gtk-vnc
    $ cd gtk-vnc
    $ git checkout 0e8b3c545ad109051501b4ff4ed548689df6e7d4
    $ NOCONFIGURE=1 ./autogen.sh
    $ ./configure --prefix=/usr --with-examples --disable-static --disable-werror
    […]
    Configure summary:
    
            Compiler ...................:  gcc
            Compiler Flags .............:  -g -O2
            Extra Link Flags ...........:  -Wl,--version-script= -Wl,--no-undefined
            Prefix......................:  /usr
    
            Python binding .............:  no
            Install example programs ...:  yes
            SASL support................:  yes
            PulseAudio support..........:  yes
            GTK+ version................:  3.0
            TLS priority................:  NORMAL

    $ sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
    $ make

And then:

    $ mkdir ../test-install
    $ fakeroot make DESTDIR=$PWD/../test-install install
    $ cd ../test-install
    $ find
    […]
    ./usr/lib/girepository-1.0
    ./usr/lib/girepository-1.0/GVnc-1.0.typelib
    ./usr/lib/girepository-1.0/GVncPulse-1.0.typelib
    ./usr/lib/girepository-1.0/GtkVnc-2.0.typelib
    […]

Yes, the configure summary says that no Python bindings are generated. However, the GIRepository entries are generated. Possibly, the GIRepository entries supersede the Python bindings. No idea, but it works. *Does it also work for you?*

**Comment by ghost** [comment]
I rebuilt gtk-vnc according to your instructions. Unfortunately it does not create the GIRepository entries. However, a quick apt-file search turned up the package `gir1.2-gtk-vnc-2.0 0.5.3-1.3ubuntu2.1` which does provide them. I installed this and bingo! a working vncdesk.
Thank you very much for your help. I could not have done it without you.
Regards
Alan

**Comment by feklee** [comment]
I'm glad that we resolved this issue together! Now I updated the documentation accordingly.
