### ISSUE TITLE
Scaling method?

### ISSUE THREAD

**Issue by mencoder** [feklee/vncdesk#6]
Hello, is it possible to change scale method (algorithm) from currently used bilinear (or whatever) to nearest-neighbour to get rid of blur? I think it's something related to gtk-vnc functions calls, but I'm not familiar with python/programming. Thanks.

**Comment by feklee** [comment]
Just contacted the maintainer of the [GTK VNC widget](https://wiki.gnome.org/Projects/gtk-vnc), which is used under the hood. Currently it’s not possible to specify the scaling filter. Let’s wait…

**Comment by feklee** [comment]
Just released version 1.6.0. It provides an option `smoothing`, which controls blur when scaling.

For this option to work, I submitted a patch to the author of gtk-vnc. He responded with: “I've pushed it to GIT master now, but don't currently have a time frame for making a new release.” In other words, you currently need the development version of gtk-vnc.
