### ISSUE TITLE
Error : Cannot read settings

### ISSUE THREAD

**Issue by jonlaokan** [feklee/vncdesk#8]
Hey,

I tried launching an instance of vncdesk but every time I get this error : 
" Cannot read settings : option values must be strings "
Here is my minimal settings.ini : 

```
[desktop]
width = 1024
height = 768
```

I tried putting the options between " " but it did not resolve this issue.
What should I do?

**Comment by feklee** [comment]
Which release did you install?

**Comment by jonlaokan** [comment]
https://aur.archlinux.org/packages/vncdesk-git/

I'm using Arch Linux, I installed it via the AUR repos.

**Comment by feklee** [comment]
The Arch install script downloaded a vncdesk development version instead of the latest release. I fixed that. Please try again with updated [`PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vncdesk-git).

**Comment by feklee** [comment]
Missed sth. Please try again.

**Comment by jonlaokan** [comment]
Amazing, it works perfectly now.
Thanks a lot!

**Comment by jonlaokan** [comment]
https://aur.archlinux.org/packages/vncdesk-git  

I'm using Arch Linux, I installed it from the Aur repos.  

## 

Jonathan Lao Kan  

Le 21 octobre 2016 à 09:53:30, Felix E. Klee (notifications@github.com(mailto:notifications@github.com)) a écrit:
